name: Waka Dev Metrics

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC+8 (16:00 UTC)
    - cron: '0 16 * * *'

jobs:
  update-readme:
    name: Update Dev Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v4
        with:
          path: assets/commits_data.pick
          key: commits-${{ hashFiles('**/.git/refs/heads/*') }}
      - uses: dexhunter/fast-waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN_NEW }}
          SYMBOL_VERSION: 2
          COMMIT_MESSAGE: "ci(auto): update dev metrics"
          SHOW_UPDATED_DATE: true
          SHOW_LANGUAGE_PER_REPO: true
          SHOW_COMMIT: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_EDITORS: true
          SHOW_TIMEZONE: true
          SHOW_PROFILE_VIEWS: true
          SHOW_TOTAL_CODE_TIME: true
          SHOW_LINES_OF_CODE: true
          SHOW_OS: true
          SHOW_PROJECTS: false
          SHOW_LOC_CHART: true
          SHOW_SHORT_INFO: true
          SECTION_NAME: devmetrics
