name: Waka Dev Metrics

on:
  workflow_dispatch:
  schedule:
    # 00:00 at UTC+8  (16:00 UTC the previous day)
    - cron: '0 16 * * *'

jobs:
  update-readme:
    name: Update Dev Metrics in README
    runs-on: ubuntu-latest

    steps:
    # ────────────────────────────────────────────────────────────────
    # 1. your profile-readme repo (implicit work-dir = $GITHUB_WORKSPACE)
    - name: Checkout profile repo
      uses: actions/checkout@v4

    # 2. pull the action's *source* so we can run it without Docker
    - name: Checkout fast-waka-readme-stats source
      uses: actions/checkout@v4
      with:
        repository: dexhunter/fast-waka-readme-stats
        path: fast-waka-readme-stats

    # 3. install Python & cache wheels
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    # 4. cache the generated assets (commit stats pickle, graphs, …)
    - name: Cache Waka assets
      uses: actions/cache@v4
      with:
        path: fast-waka-readme-stats/assets
        key: commits-v1-${{ runner.os }}-${{ github.ref_name }}
        restore-keys: |
          commits-v1-

    # 5. install dependencies of the action
    - name: Install action requirements
      run: pip install -r requirements.txt
      working-directory: fast-waka-readme-stats

    # 6. run the action's Python entry-point
    - name: Run fast-waka-readme-stats
      working-directory: fast-waka-readme-stats
      env:
        # mandatory tokens
        INPUT_WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        INPUT_GH_TOKEN:          ${{ secrets.GH_TOKEN_NEW }}

        # behaviour flags – identical to your previous `with:` block
        INPUT_SECTION_NAME:      devmetrics
        INPUT_SYMBOL_VERSION:    '2'
        INPUT_COMMIT_MESSAGE:    'ci(auto): update dev metrics'

        INPUT_SHOW_UPDATED_DATE:        'True'
        INPUT_SHOW_LANGUAGE_PER_REPO:   'True'
        INPUT_SHOW_COMMIT:              'True'
        INPUT_SHOW_DAYS_OF_WEEK:        'True'
        INPUT_SHOW_EDITORS:             'True'
        INPUT_SHOW_TIMEZONE:            'True'
        INPUT_SHOW_PROFILE_VIEWS:       'True'
        INPUT_SHOW_TOTAL_CODE_TIME:     'True'
        INPUT_SHOW_LINES_OF_CODE:       'True'
        INPUT_SHOW_OS:                  'True'
        INPUT_SHOW_PROJECTS:            'False'
        INPUT_SHOW_LOC_CHART:           'True'
        INPUT_SHOW_SHORT_INFO:          'True'

        # set to 'True' only when you want **preview/no-commit** runs
        DEBUG_RUN: 'False'
        INPUT_IGNORED_REPOS: "very-secret-repo,another_one"

      run: |
        python sources/main.py
