name: Update Dev Metrics

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC+8 (16:00 UTC)
    - cron: '0 16 * * *'

jobs:
  update-readme:
    name: Update Dev Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN_NEW }}
          SYMBOL_VERSION: 2
          COMMIT_EMAIL: i@dex.moe
          COMMIT_USERNAME: "dexhunter"
          SHOW_UPDATED_DATE: true
          SHOW_LANGUAGE_PER_REPO: true
          SHOW_COMMIT: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_EDITORS: true
          SHOW_TIMEZONE: true
          SHOW_PROFILE_VIEWS: false
          SHOW_TOTAL_CODE_TIME: false
          SHOW_LINES_OF_CODE: false
          SHOW_OS: true
          SHOW_PROJECTS: false
          SHOW_LOC_CHART: false
          SHOW_SHORT_INFO: false