name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          CODE_LANG: python # optional
          SHOW_TIME: true # optional
          SHOW_TOTAL: true # optional
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿ #optional
