name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs once daily at 12am GMT+8 (16:00 UTC)
    - cron: "0 16 * * *"

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          SECTION_NAME: defaultwaka # optional
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          CODE_LANG: python # optional
          SHOW_TIME: true # optional
          SHOW_TOTAL: true # optional
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿ # optional
          LANG_COUNT: 25 # optional
          SHOW_TITLE: true # optional
          TIME_RANGE: all_time # optional
          COMMIT_MESSAGE: "ci(auto): update wakatime metrics"